# Generated by Django 2.2.5 on 2019-09-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('decription', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='decription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
