# Generated by Django 2.2.5 on 2019-12-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cat',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
